#define LTMM_SERIAL_NUMBER       L"MySerial"
#define DVD_SERIAL_NUMBER        L"MySerial"
#define STREAMING_SERIAL_NUMBER  L"MySerial"
#define MPEG2_TRANSPORT_DEMUX_SERIAL_NUMBER L"MySerial"
#define MPEG2_TRANSPORT_MUX_SERIAL_NUMBER L"MySerial"
#define UDP_SINK_SERIAL_NUMBER L"MySerial"
#define FLV_DEMUX_SERIAL_NUMBER L"MySerial"
#define FLV_MUX_SERIAL_NUMBER L"MySerial"
#define THEORA_DECODER_SERIAL_NUMBER L"MySerial"
#define THEORA_ENCODER_SERIAL_NUMBER L"MySerial"
#define DICOM_WRITER_SERIAL_NUMBER L"MySerial"
#define DICOM_READER_SERIAL_NUMBER L"MySerial"
#define MCMP_CODEC_SERIAL_NUMBER L"MySerial"
#define MCMW_CODEC_SERIAL_NUMBER L"MySerial"
#define MJ2K_CODEC_SERIAL_NUMBER L"MySerial"
#define H263_CODEC_SERIAL_NUMBER L"MySerial"

LPCWSTR ppszBaseKeys[] =
{
   LTMM_SERIAL_NUMBER,
   DVD_SERIAL_NUMBER,
   STREAMING_SERIAL_NUMBER,
   MPEG2_TRANSPORT_DEMUX_SERIAL_NUMBER,
   MPEG2_TRANSPORT_MUX_SERIAL_NUMBER,
   UDP_SINK_SERIAL_NUMBER,
   FLV_DEMUX_SERIAL_NUMBER,
   FLV_MUX_SERIAL_NUMBER,
   THEORA_DECODER_SERIAL_NUMBER,
   THEORA_ENCODER_SERIAL_NUMBER,
   DICOM_WRITER_SERIAL_NUMBER,
   DICOM_READER_SERIAL_NUMBER,
   MCMP_CODEC_SERIAL_NUMBER,
   MCMW_CODEC_SERIAL_NUMBER,
   MJ2K_CODEC_SERIAL_NUMBER,
   H263_CODEC_SERIAL_NUMBER,
   NULL
};
